'use client';

import { useEffect, useState } from 'react';
import { defaultWebsiteAppearance, mergeWebsiteAppearance, type WebsiteAppearance } from '@/src/types/appearance';

const presets: Record<string, WebsiteAppearance> = {
  default: defaultWebsiteAppearance,
  warm: mergeWebsiteAppearance({ preset: 'warm', colors: { primary: '#ea580c', accent: '#c2410c', background: '#fff7ed', surface: '#ffffff', buttonBackground: '#9a3412', link: '#c2410c' } }),
  dark: mergeWebsiteAppearance({ preset: 'dark', colors: { primary: '#fbbf24', accent: '#f59e0b', background: '#1c1917', surface: '#292524', headerBackground: '#1c1917', headerText: '#fafaf9', footerBackground: '#09090b', footerText: '#e4e4e7', body: '#d6d3d1', heading: '#fafaf9', buttonBackground: '#f59e0b', buttonText: '#1c1917', link: '#fbbf24', border: '#57534e' } }),
  elegant: mergeWebsiteAppearance({ preset: 'elegant', colors: { primary: '#be123c', accent: '#9f1239', background: '#fff1f2', surface: '#ffffff', buttonBackground: '#881337', link: '#be123c' }, typography: { fontFamily: 'serif' } }),
  minimal: mergeWebsiteAppearance({ preset: 'minimal', colors: { primary: '#0f766e', accent: '#0f766e', background: '#f8fafc', surface: '#ffffff', buttonBackground: '#0f172a', link: '#0f766e', border: '#cbd5e1' }, radius: 'soft', shadow: 'none' }),
};

const colorFields = Object.keys(defaultWebsiteAppearance.colors) as Array<keyof WebsiteAppearance['colors']>;

export default function AppearanceEditor() {
  const [appearance, setAppearance] = useState<WebsiteAppearance>(defaultWebsiteAppearance);
  const [saved, setSaved] = useState<WebsiteAppearance>(defaultWebsiteAppearance);
  const [mode, setMode] = useState<'desktop' | 'mobile'>('desktop');
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => { fetch('/api/admin/settings/appearance').then((response) => response.json()).then((data) => { if (data.success) { const value = mergeWebsiteAppearance(data.data); setAppearance(value); setSaved(value); } else setError(data.error || 'Unable to load appearance.'); }).catch(() => setError('Unable to load appearance.')).finally(() => setLoading(false)); }, []);

  function updateColor(field: keyof WebsiteAppearance['colors'], value: string) { setAppearance((current) => ({ ...current, preset: 'custom', colors: { ...current.colors, [field]: value } })); }
  async function publish() { setBusy(true); setError(null); setMessage(null); try { const response = await fetch('/api/admin/settings/appearance', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ appearance }) }); const data = await response.json(); if (!response.ok || !data.success) throw new Error(data.error || 'Could not save theme.'); const next = mergeWebsiteAppearance(data.data); setAppearance(next); setSaved(next); setMessage('Theme published successfully.'); } catch (publishError) { setError(publishError instanceof Error ? publishError.message : 'Could not save theme.'); } finally { setBusy(false); } }
  async function resetPublished() { if (!window.confirm('Restore the default Pizza Vizza design? Your currently published custom theme will be replaced.')) return; setBusy(true); setError(null); try { const response = await fetch('/api/admin/settings/appearance', { method: 'DELETE' }); const data = await response.json(); if (!response.ok || !data.success) throw new Error(data.error || 'Could not reset theme.'); const next = mergeWebsiteAppearance(data.data); setAppearance(next); setSaved(next); setMessage('Default theme restored.'); } catch (resetError) { setError(resetError instanceof Error ? resetError.message : 'Could not reset theme.'); } finally { setBusy(false); } }
  if (loading) return <p className="text-sm text-stone-500">Loading appearance...</p>;
  const previewStyle = { ...appearance.colors, '--preview-bg': appearance.colors.background } as React.CSSProperties;
  return <div className="space-y-5">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-semibold">Website Appearance</h2><p className="text-sm text-stone-500">Preview changes locally. Publish only when ready.</p></div><div className="flex gap-2"><button type="button" onClick={() => setMode('desktop')} className="btn">Desktop</button><button type="button" onClick={() => setMode('mobile')} className="btn">Mobile</button></div></div>
    <div className="grid gap-5 xl:grid-cols-[1fr_1.15fr]">
      <div className="space-y-4">
        <section className="rounded-2xl border border-stone-200 bg-stone-50 p-4"><h3 className="font-semibold">Theme presets</h3><div className="mt-3 grid grid-cols-2 gap-2">{Object.keys(presets).map((key) => <button key={key} type="button" onClick={() => setAppearance(mergeWebsiteAppearance(presets[key]))} className={`rounded-xl border p-3 text-left text-sm ${appearance.preset === key ? 'border-amber-500 bg-amber-50' : 'border-stone-200 bg-white'}`}>{key === 'default' ? 'Pizza Vizza Default' : key[0].toUpperCase() + key.slice(1)}</button>)}</div></section>
        <section className="rounded-2xl border border-stone-200 bg-stone-50 p-4"><h3 className="font-semibold">Colors</h3><div className="mt-3 grid gap-3 sm:grid-cols-2">{colorFields.map((field) => <label key={field} className="text-xs font-medium text-stone-600">{field.replace(/[A-Z]/g, (letter) => ` ${letter}`).replace(/^./, (letter) => letter.toUpperCase())}<span className="mt-1 flex items-center gap-2"><input type="color" value={appearance.colors[field]} onChange={(event) => updateColor(field, event.target.value)} className="h-9 w-10 rounded border border-stone-300" /><input value={appearance.colors[field]} onChange={(event) => updateColor(field, event.target.value)} className="input min-w-0 flex-1 font-mono" pattern="#[0-9a-fA-F]{6}" /></span></label>)}</div></section>
        <section className="rounded-2xl border border-stone-200 bg-stone-50 p-4"><h3 className="font-semibold">Visual style</h3><div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="text-sm">Radius<select className="input mt-1" value={appearance.radius} onChange={(event) => setAppearance({ ...appearance, radius: event.target.value as WebsiteAppearance['radius'] })}><option value="sharp">Sharp</option><option value="soft">Soft</option><option value="rounded">Rounded</option><option value="extra-rounded">Extra rounded</option></select></label><label className="text-sm">Shadow<select className="input mt-1" value={appearance.shadow} onChange={(event) => setAppearance({ ...appearance, shadow: event.target.value as WebsiteAppearance['shadow'] })}><option value="none">None</option><option value="subtle">Subtle</option><option value="medium">Medium</option><option value="strong">Strong</option></select></label></div></section>
      </div>
      <div><div className={`mx-auto overflow-hidden rounded-2xl border border-stone-300 bg-[var(--preview-bg)] shadow-lg ${mode === 'mobile' ? 'max-w-sm' : 'max-w-none'}`} style={previewStyle}><div className="flex items-center justify-between border-b p-4" style={{ background: appearance.colors.headerBackground, color: appearance.colors.headerText, borderColor: appearance.colors.border }}><strong>Pizza Vizza</strong><span className="text-sm">Home&nbsp;&nbsp; Menu&nbsp;&nbsp; Account</span></div><div className="space-y-4 p-5"><div><p className="text-xs font-semibold uppercase tracking-widest" style={{ color: appearance.colors.accent }}>Fresh from the oven</p><h3 className="mt-2 text-2xl font-bold" style={{ color: appearance.colors.heading }}>A better way to order</h3><p className="mt-2" style={{ color: appearance.colors.body }}>Preview the live customer experience before publishing.</p></div><div className="rounded-xl border p-4" style={{ background: appearance.colors.surface, borderColor: appearance.colors.border }}><p className="font-semibold" style={{ color: appearance.colors.heading }}>Margherita Pizza</p><p className="mt-1 text-sm" style={{ color: appearance.colors.body }}>Classic tomato, mozzarella and basil.</p><button type="button" className="btn mt-4" style={{ background: appearance.colors.buttonBackground, color: appearance.colors.buttonText }}>Add to cart</button></div><input className="w-full rounded-lg border px-3 py-2" style={{ background: appearance.colors.surface, color: appearance.colors.body, borderColor: appearance.colors.border }} placeholder="Preview input" /></div><div className="p-4 text-sm" style={{ background: appearance.colors.footerBackground, color: appearance.colors.footerText }}>Pizza Vizza <span style={{ color: appearance.colors.footerAccent }}>• Help &amp; support</span></div></div></div>
    </div>
    {message ? <p className="rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700">{message}</p> : null}{error ? <p className="rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{error}</p> : null}
    <div className="flex flex-wrap justify-end gap-2"><button type="button" className="rounded-full border border-stone-300 px-4 py-2 text-sm font-semibold" onClick={() => setAppearance(saved)}>Reset changes</button><button type="button" className="rounded-full border border-rose-300 px-4 py-2 text-sm font-semibold text-rose-700" onClick={resetPublished} disabled={busy}>Reset published theme</button><button type="button" className="btn" onClick={publish} disabled={busy}>{busy ? 'Publishing...' : 'Save & publish'}</button></div>
  </div>;
}