'use client';

import { useEffect, useState } from 'react';
type Room = { id?: string; _id?: string; name: string; bookingDurationMinutes: number };
export default function ManualBookingForm() {
  const [rooms, setRooms] = useState<Room[]>([]); const [message, setMessage] = useState(''); const [form, setForm] = useState({ name: '', mobile: '', email: '', roomId: '', bookingDate: new Date().toISOString().slice(0, 10), startTime: '', guestCount: '2', roomCount: '1', durationMinutes: '60', paymentMethod: 'COD', note: '' });
  useEffect(() => { fetch('/api/admin/dining/rooms').then((response) => response.json()).then((data) => setRooms(data.data || [])).catch(() => setRooms([])); }, []);
  async function submit(event: React.FormEvent) { event.preventDefault(); const response = await fetch('/api/admin/bookings', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...form, guestCount: Number(form.guestCount), roomCount: Number(form.roomCount), durationMinutes: Number(form.durationMinutes) }) }); const data = await response.json(); setMessage(response.ok ? `Booking ${data.data.bookingNumber} created.` : data.error || 'Unable to create booking.'); }
  return <form onSubmit={submit} className="rounded-2xl border border-amber-200 bg-amber-50 p-4"><h2 className="font-semibold">Manual / walk-in reservation</h2><div className="mt-3 grid gap-3 sm:grid-cols-3"><input required placeholder="Customer name" value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} className="rounded-xl border px-3 py-2" /><input required placeholder="Mobile" value={form.mobile} onChange={(event) => setForm({ ...form, mobile: event.target.value })} className="rounded-xl border px-3 py-2" /><input placeholder="Email (optional)" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} className="rounded-xl border px-3 py-2" /></div><div className="mt-3 grid gap-3 sm:grid-cols-4"><select required value={form.roomId} onChange={(event) => setForm({ ...form, roomId: event.target.value })} className="rounded-xl border px-3 py-2"><option value="">Room</option>{rooms.map((room) => <option key={room.id || room._id} value={room.id || room._id}>{room.name}</option>)}</select><input required type="date" value={form.bookingDate} onChange={(event) => setForm({ ...form, bookingDate: event.target.value })} className="rounded-xl border px-3 py-2" /><input required type="time" value={form.startTime} onChange={(event) => setForm({ ...form, startTime: event.target.value })} className="rounded-xl border px-3 py-2" /><input required type="number" min="1" value={form.guestCount} onChange={(event) => setForm({ ...form, guestCount: event.target.value })} className="rounded-xl border px-3 py-2" placeholder="Guests" /></div><div className="mt-3 grid gap-3 sm:grid-cols-3"><input type="number" min="1" value={form.roomCount} onChange={(event) => setForm({ ...form, roomCount: event.target.value })} className="rounded-xl border px-3 py-2" placeholder="Rooms" /><input type="number" min="15" value={form.durationMinutes} onChange={(event) => setForm({ ...form, durationMinutes: event.target.value })} className="rounded-xl border px-3 py-2" placeholder="Duration" /><input placeholder="Note" value={form.note} onChange={(event) => setForm({ ...form, note: event.target.value })} className="rounded-xl border px-3 py-2" /></div><button type="submit" className="mt-3 rounded-xl bg-amber-600 px-4 py-2 text-sm font-semibold text-white">Create reservation</button>{message ? <p className="mt-3 text-sm text-stone-700">{message}</p> : null}</form>;
}
