'use client';

import { useState } from 'react';

type ReceiptItem = { name: string; quantity: number; unitPrice: number; subtotal: number; selectedOptions?: Array<{ groupName: string; optionName: string; price: number }> };
type ReceiptData = { orderNumber: string; createdAt: string; fulfillmentType: string; customerName: string; customerMobile?: string | null; customerEmail?: string | null; items: ReceiptItem[]; subtotal: number; discount: number; walletAmount: number; deliveryCharge: number; additionalCharges: number; totalAmount: number; paidAmount: number; amountDue: number; paymentMethod?: string | null; paymentStatus: string; address?: { addressLine1: string; addressLine2?: string | null; landmark?: string | null; city: string; state: string; postalCode: string } | null; restaurantName: string; restaurantLogo?: string | null; restaurantAddress: string; restaurantPhone?: string | null; restaurantEmail?: string | null };

function money(value: number) { return `INR ${Number(value || 0).toFixed(2)}`; }
function text(data: ReceiptData) { return [`Pizza Vizza Order`, `Order: ${data.orderNumber}`, `Type: ${data.fulfillmentType}`, `Total: ${money(data.totalAmount)}`, `Payment: ${data.paymentStatus}`, `View Receipt: ${window.location.toString()}`].join('\n'); }

export default function ReceiptActions({ data }: { data: ReceiptData }) {
  const [message, setMessage] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);
  const fileName = `pizza-vizza-${data.orderNumber}`;

  async function downloadImage() {
    setBusy(true); setMessage(null);
    try {
      const canvas = document.createElement('canvas');
      const scale = 2; const width = 760; const lineHeight = 34; const itemLines = data.items.reduce((count, item) => count + 1 + (item.selectedOptions?.length || 0), 0);
      canvas.width = width * scale; canvas.height = Math.max(900, (620 + itemLines * lineHeight) * scale);
      const ctx = canvas.getContext('2d'); if (!ctx) throw new Error('Receipt image is unavailable.'); ctx.scale(scale, scale); ctx.fillStyle = '#fafaf9'; ctx.fillRect(0, 0, width, canvas.height / scale); ctx.fillStyle = '#1c1917'; ctx.font = '700 32px Arial'; ctx.fillText(data.restaurantName, 48, 64); ctx.font = '600 22px Arial'; ctx.fillText('ORDER RECEIPT', 48, 108); ctx.font = '18px Arial'; ctx.fillStyle = '#57534e'; ctx.fillText(`${data.orderNumber}  |  ${new Date(data.createdAt).toLocaleString()}`, 48, 144); ctx.fillText(`${data.fulfillmentType}  |  ${data.customerName}`, 48, 174); let y = 238; ctx.fillStyle = '#1c1917'; ctx.font = '700 20px Arial'; ctx.fillText('Items', 48, y); y += 38; ctx.font = '18px Arial'; data.items.forEach((item) => { ctx.fillText(`${item.quantity} x ${item.name}`, 48, y); ctx.textAlign = 'right'; ctx.fillText(money(item.subtotal), width - 48, y); ctx.textAlign = 'left'; y += lineHeight; item.selectedOptions?.forEach((option) => { ctx.fillStyle = '#78716c'; ctx.font = '15px Arial'; ctx.fillText(`+ ${option.groupName}: ${option.optionName}`, 72, y); y += 25; ctx.fillStyle = '#1c1917'; ctx.font = '18px Arial'; }); }); y += 20; ctx.strokeStyle = '#d6d3d1'; ctx.beginPath(); ctx.moveTo(48, y); ctx.lineTo(width - 48, y); ctx.stroke(); y += 42; ctx.font = '18px Arial'; [['Subtotal', data.subtotal], ['Discount', -data.discount], ['Wallet used', -data.walletAmount], ['Delivery charge', data.deliveryCharge], ['Other charges', data.additionalCharges]].forEach(([label, value]) => { if (Number(value) !== 0) { ctx.fillText(String(label), 48, y); ctx.textAlign = 'right'; ctx.fillText(money(Number(value)), width - 48, y); ctx.textAlign = 'left'; y += 30; } }); ctx.font = '700 24px Arial'; ctx.fillText('TOTAL', 48, y + 12); ctx.textAlign = 'right'; ctx.fillText(money(data.totalAmount), width - 48, y + 12); ctx.textAlign = 'left'; y += 62; ctx.font = '18px Arial'; ctx.fillText(`Payment: ${data.paymentMethod || 'Not specified'} (${data.paymentStatus})`, 48, y); ctx.fillText(`Paid: ${money(data.paidAmount)}   Due: ${money(data.amountDue)}`, 48, y + 32); y += 78; if (data.address) { ctx.font = '700 18px Arial'; ctx.fillText('Delivery address', 48, y); ctx.font = '16px Arial'; ctx.fillText(`${data.address.addressLine1}${data.address.landmark ? `, ${data.address.landmark}` : ''}`, 48, y + 28); ctx.fillText(`${data.address.city}, ${data.address.state} ${data.address.postalCode}`, 48, y + 54); y += 96; } ctx.fillStyle = '#78716c'; ctx.font = '16px Arial'; ctx.fillText('Thank you for ordering from Pizza Vizza!', 48, y); const link = document.createElement('a'); link.download = `${fileName}.png`; link.href = canvas.toDataURL('image/png'); link.click(); setMessage('Receipt image downloaded.');
    } catch (error) { setMessage(error instanceof Error ? error.message : 'Receipt image failed.'); } finally { setBusy(false); }
  }

  async function share() { setMessage(null); try { const value = text(data); if (navigator.share) { await navigator.share({ title: `Pizza Vizza ${data.orderNumber}`, text: value }); setMessage('Receipt shared.'); } else { await navigator.clipboard.writeText(value); setMessage('Receipt link copied.'); } } catch (error) { if (!(error instanceof Error && error.name === 'AbortError')) setMessage('Sharing is unavailable on this device.'); } }
  async function downloadPdf() { setBusy(true); setMessage(null); try { const response = await fetch(`/api/account/orders/${encodeURIComponent(data.orderNumber)}/receipt.pdf`, { credentials: 'include' }); if (!response.ok) throw new Error('Receipt PDF could not be generated.'); const blob = await response.blob(); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = `${fileName}.pdf`; link.click(); URL.revokeObjectURL(link.href); setMessage('Receipt PDF downloaded.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Receipt PDF failed.'); } finally { setBusy(false); } }
  function whatsapp() { window.open(`https://wa.me/?text=${encodeURIComponent(text(data))}`, '_blank', 'noopener,noreferrer'); }

  return <div className="mt-6 rounded-2xl border border-amber-200 bg-amber-50 p-4 print:hidden"><h2 className="font-semibold text-stone-900">Your Receipt</h2><div className="mt-3 flex flex-wrap gap-2"><button type="button" disabled={busy} onClick={downloadPdf} className="min-h-11 rounded-xl bg-amber-600 px-4 py-2 text-sm font-semibold text-white">Download PDF</button><button type="button" disabled={busy} onClick={() => void downloadImage()} className="min-h-11 rounded-xl border border-stone-300 bg-white px-4 py-2 text-sm font-semibold text-stone-700">Download Image</button><button type="button" onClick={() => window.print()} className="min-h-11 rounded-xl border border-stone-300 bg-white px-4 py-2 text-sm font-semibold text-stone-700">Print Receipt</button><button type="button" onClick={() => void share()} className="min-h-11 rounded-xl border border-stone-300 bg-white px-4 py-2 text-sm font-semibold text-stone-700">Share Receipt</button><button type="button" onClick={whatsapp} className="min-h-11 rounded-xl bg-emerald-600 px-4 py-2 text-sm font-semibold text-white">Share on WhatsApp</button></div>{message ? <p role="status" className="mt-3 text-sm text-stone-700">{message}</p> : null}</div>;
}
