'use client';

import { useEffect, useState } from 'react';

type Order = { orderNumber: string; orderStatus: string; customerSnapshot?: { name?: string; mobile?: string | null }; deliveryAddress?: { addressLine1?: string; city?: string; state?: string; latitude?: number | null; longitude?: number | null } | null; totalAmount: number };

export default function DeliveryDashboard() {
  const [orders, setOrders] = useState<Order[]>([]);
  const [message, setMessage] = useState('');
  async function load() { const response = await fetch('/api/admin/operations', { cache: 'no-store' }); if (response.ok) setOrders((await response.json()).data.orders || []); }
  useEffect(() => { const initial = window.setTimeout(() => void load(), 0); const timer = window.setInterval(() => void load(), 15000); return () => { window.clearTimeout(initial); window.clearInterval(timer); }; }, []);
  async function update(orderNumber: string, status: string) { const response = await fetch(`/api/admin/orders/${orderNumber}/status`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ status }) }); setMessage(response.ok ? `${orderNumber} updated` : (await response.json()).error || 'Update failed'); if (response.ok) await load(); }
  return <div className="space-y-5"><header><p className="text-sm font-semibold uppercase tracking-[0.2em] text-amber-600">Delivery staff</p><h1 className="mt-1 text-3xl font-semibold">My deliveries</h1><p className="mt-2 text-sm text-stone-600">Only orders assigned to your account are shown.</p></header>{message ? <p className="rounded-xl bg-emerald-50 p-3 text-sm text-emerald-800">{message}</p> : null}<div className="grid gap-4">{orders.filter((order) => !['COMPLETED', 'CANCELLED', 'REJECTED'].includes(order.orderStatus)).map((order) => <article key={order.orderNumber} className="rounded-2xl border border-stone-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-bold">{order.orderNumber}</h2><p className="text-sm text-stone-600">{order.customerSnapshot?.name || 'Customer'} · {order.customerSnapshot?.mobile || 'No phone'}</p></div><span className="rounded-full bg-sky-50 px-3 py-1 text-xs font-bold text-sky-800">{order.orderStatus}</span></div>{order.deliveryAddress ? <p className="mt-4 text-sm text-stone-700">{order.deliveryAddress.addressLine1}, {order.deliveryAddress.city}, {order.deliveryAddress.state}</p> : <p className="mt-4 text-sm text-stone-500">Pickup order</p>}<div className="mt-5 flex flex-wrap gap-2">{order.orderStatus === 'READY' ? <button onClick={() => void update(order.orderNumber, 'OUT_FOR_DELIVERY')} className="min-h-11 rounded-xl bg-amber-600 px-4 text-sm font-bold text-white">Start delivery</button> : null}{order.orderStatus === 'OUT_FOR_DELIVERY' ? <button onClick={() => void update(order.orderNumber, 'DELIVERED')} className="min-h-11 rounded-xl bg-emerald-600 px-4 text-sm font-bold text-white">Mark delivered</button> : null}{order.customerSnapshot?.mobile ? <a href={`tel:${order.customerSnapshot.mobile}`} className="inline-flex min-h-11 items-center rounded-xl border px-4 text-sm font-bold">Call customer</a> : null}{order.deliveryAddress?.latitude && order.deliveryAddress.longitude ? <a target="_blank" rel="noreferrer" href={`https://www.google.com/maps/dir/?api=1&destination=${order.deliveryAddress.latitude},${order.deliveryAddress.longitude}`} className="inline-flex min-h-11 items-center rounded-xl border px-4 text-sm font-bold">Navigate</a> : null}</div></article>)}</div></div>;
}
