'use client';

import { useEffect, useState } from 'react';

type Order = { orderNumber: string; orderStatus: string; fulfillmentType: string; customerSnapshot?: { name?: string }; items?: Array<{ name: string; quantity: number; selectedOptions?: Array<{ optionName: string }> }>; customerNote?: string | null };

const statuses = ['PENDING', 'CONFIRMED', 'PREPARING', 'READY', 'COMPLETED', 'CANCELLED'];

export default function KitchenDashboard() {
  const [orders, setOrders] = useState<Order[]>([]);
  const [message, setMessage] = useState('');
  async function load() { const response = await fetch('/api/admin/operations', { cache: 'no-store' }); if (response.ok) setOrders((await response.json()).data.orders || []); }
  useEffect(() => { const initial = window.setTimeout(() => void load(), 0); const timer = window.setInterval(() => void load(), 15000); return () => { window.clearTimeout(initial); window.clearInterval(timer); }; }, []);
  async function update(orderNumber: string, status: string) { const response = await fetch(`/api/admin/orders/${orderNumber}/status`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ status }) }); setMessage(response.ok ? `${orderNumber} updated` : (await response.json()).error || 'Update failed'); if (response.ok) await load(); }
  return <div className="space-y-5"><header><p className="text-sm font-semibold uppercase tracking-[0.2em] text-amber-600">Kitchen display</p><h1 className="mt-1 text-3xl font-semibold">Preparation queue</h1><p className="mt-2 text-sm text-stone-600">Live orders for the kitchen team. Refreshes automatically.</p></header>{message ? <p className="rounded-xl bg-emerald-50 p-3 text-sm text-emerald-800">{message}</p> : null}<div className="grid gap-4 lg:grid-cols-3">{orders.filter((order) => statuses.includes(order.orderStatus)).map((order) => <article key={order.orderNumber} className="rounded-2xl border border-stone-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><h2 className="text-lg font-bold">{order.orderNumber}</h2><p className="text-sm text-stone-500">{order.customerSnapshot?.name || 'Customer'} · {order.fulfillmentType}</p></div><span className="rounded-full bg-amber-50 px-3 py-1 text-xs font-bold text-amber-800">{order.orderStatus}</span></div><ul className="mt-4 space-y-2 text-sm">{(order.items || []).map((item, index) => <li key={`${item.name}-${index}`}><span className="font-semibold">{item.quantity} ×</span> {item.name}{item.selectedOptions?.length ? <span className="block pl-6 text-xs text-stone-500">{item.selectedOptions.map((option) => option.optionName).join(', ')}</span> : null}</li>)}</ul>{order.customerNote ? <p className="mt-4 rounded-xl bg-amber-50 p-3 text-xs text-amber-900">Note: {order.customerNote}</p> : null}<div className="mt-5 grid grid-cols-2 gap-2">{order.orderStatus === 'PENDING' ? <button onClick={() => void update(order.orderNumber, 'CONFIRMED')} className="min-h-11 rounded-xl bg-emerald-600 px-3 text-sm font-bold text-white">Accept</button> : null}{order.orderStatus === 'CONFIRMED' ? <button onClick={() => void update(order.orderNumber, 'PREPARING')} className="min-h-11 rounded-xl bg-amber-600 px-3 text-sm font-bold text-white">Start prep</button> : null}{order.orderStatus === 'PREPARING' ? <button onClick={() => void update(order.orderNumber, 'READY')} className="min-h-11 rounded-xl bg-sky-600 px-3 text-sm font-bold text-white">Mark ready</button> : null}<button onClick={() => void update(order.orderNumber, 'CANCELLED')} className="min-h-11 rounded-xl border border-rose-200 px-3 text-sm font-bold text-rose-700">Cancel</button></div></article>)}</div></div>;
}
